### ISSUE TITLE
Playing with CSKG Grounding Notebook: 'grounding/groundcn' and 'grounding/groundcskg' folders empty causing failed imports

### ISSUE THREAD

**Issue by jaleedkhan** [usc-isi-i2/cskg#16]
Issues while running [Playing with CSKG Grounding Notebook](https://github.com/usc-isi-i2/cskg/blob/master/tutorial/Playing%20with%20grounding.ipynb):

- Numberbatch file and BERT embeddings were downloaded and placed into the directory ../output/embeddings, and gunzip-ed.
- Needed to install pygraphviz package before running the notebook:
!apt-get update -y
!apt-get install -y graphviz libgraphviz-dev graphviz-dev pkg-config
!python -m pip install pygraphviz
- The ‘groundcn’ and ‘groundcskg’ folders in the ‘../grounding/’ folder are empty and do not contain ‘graphify’, due to which “from groundcn.graphify import graphify”, “from groundcn.graphify import link” and “from groundcskg.graphify import link” throw the ModuleNotFoundError error and rest of the code does not execute, as shown in [screencapture5.pdf](https://github.com/usc-isi-i2/cskg/files/7111763/screencapture5.pdf) attached herewith.

**Comment by filievski** [comment]
@jaleedkhan thanks for reporting this. Somehow my last commit of the grounding code did not go through properly. Now I re-committed the code, so please pull again and re-try. 
Once this works for you too, I will take a look into how to streamline the package requirements across submodules.
