### ISSUE TITLE
About mw:SameAs relation 

### ISSUE THREAD

**Issue by yayamamo** [usc-isi-i2/cskg#82]
I read CSKG paper ( https://doi.org/10.48550/arXiv.2012.11490 ), and the authors explained that  there were `mw:SameAs` relationships in the data.
So, I downloaded a CSKG file (`cskg.tsv.gz` ) from  https://zenodo.org/record/4331372, however I couldn't find them.
I tried the following commands.
```
% zgrep mw:SameAs cskg.tsv.gz
```
and
```
% kgtk query -i cskg.tsv.gz --match '()-[z{relation:"mw:SameAs"}]->()'
```
Could you let me know where I can find a dataset which contained that relationship?

**Comment by yayamamo** [comment]
I've found there are in the `cskg_star.tsv.gz`.
However, 'cskg_star.tsv.gz' doesn't seem to contain the entire `cskg.tsv.gz` because one has
```
/c/en/clavier/n/wn/artifact-mw:MayHaveProperty-/c/en/piano/a/wn-0000	/c/en/clavier/n/wn/artifact	mw:MayHaveProperty	/c/en/piano/a/wn	piano	piano	may have property		VG	
```
while the other has
```
wn:piano.n.01-mw:MayHaveProperty-wn:piano.a.01-0000	wn:piano.n.01	mw:MayHaveProperty	wn:piano.a.01	piano	piano	may have property		VG	
```
.
The both denote a semantically identical triple, but their expressions are different from each other.
Is my assumption correct that the entire knowledge graph of cskg.tsv.gz is contained by cskg_star.tsv.gz while some notations of them are different?

**Comment by filievski** [comment]
You can find the answer in Line 36 of the `create_cskg.sh` script:
https://github.com/usc-isi-i2/cskg/blob/master/consolidation/create_cskg.sh#L36

Namely, cskg_star is an intermediate file that includes the SameAs mappings. After applying these identity mappings to combine the nodes, we get CSKG and we drop the SameAs mappings. This is why you see the mappings in the "star" version and not in the final version. 

This combination of the nodes is the reason why the semantically equivalent statements look different in the two graph files.
